name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Heroku
      uses: akhileshns/heroku-deploy@v3.0.1
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: youremail@example.com

    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:main
